---
version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  groups:
    patch:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "patch"
- package-ecosystem: 'terraform'
  directory: '/'
  schedule:
    interval: 'daily'
