# .github/workflows/template-sync.yml
name: Template Sync

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  template-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Sync with dependent repositories
        uses: ahmadnassri/action-template-repository-sync@v2
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          config: .github/template-sync.yml
